name: Generate static org-roam-ui page
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  actions: read
  contents: read
  pages: write
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Generate org-roam-ui page
        uses: ikoamu/org-roam-ui-hosting@main
        with:
          org-roam-db-filename: org-roam.db
          deploy-to-pages: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


